version: '3'

services:
  app:
    image: node:12.19.0
    ports: ['3000:3000']
    working_dir: /app
    command: yarn run start
    tty: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v6

  infra:
    build:
      context: .
      dockerfile: ./containers/infra/Dockerfile
    volumes:
      - .:/app
      - aws:/root/.aws
    env_file:
      - .env.compose

volumes:
  aws:
  yarn_cache:
  node_modules:
