version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  awscli:
    docker:
      - image: amazon/aws-cli:2.0.61
  terraform:
    docker:
      - image: hashicorp/terraform:0.13.5

commands:
  terraform:
    parameters:
      stage:
        type: string
      command:
        type: string
    steps:
      - run:
          name: terraform << parameters.command >> - << parameters.stage >>
          command: |
            cd ~/project/terraform/envs/<< parameters.stage >>
            terraform << parameters.command >>

  yarn_install:
    steps:
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --check-files
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  setup_aws_config:
    steps:
      - run:
          name: create aws/credentials aws/config
          command: |
            mkdir -p ~/.aws
            echo '[default]'                                       > ~/.aws/credentials
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}"         >> ~/.aws/credentials
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            echo '[default]'                                       > ~/.aws/config
            echo "region = us-east-1"                             >> ~/.aws/config

jobs:
  terraform_plan:
    executor: terraform
    steps:
      - checkout
      - run: apk --update add curl bash
      - setup_aws_config
      - terraform:
          stage: dev
          command: init
      - terraform:
          stage: dev
          command: plan
      - terraform:
          stage: prod
          command: init
      - terraform:
          stage: prod
          command: plan
      - slack/status

  terraform_apply:
    executor: terraform
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - run: apk --update add curl bash
      - setup_aws_config
      - terraform:
          stage: << parameters.stage >>
          command: init
      - terraform:
          stage: << parameters.stage >>
          command: apply -auto-approve
      - slack/status

workflows:
  build:
    jobs:
      - terraform_plan

      - slack/approval-notification:
          requires: [terraform_plan]
      - approval_deploy:
          type: approval
          requires: [terraform_plan]

      - terraform_apply:
          name: terraform_apply_dev
          stage: dev
          requires: [approval_deploy]
          filters:
            branches:
              ignore: main

      - terraform_apply:
          name: terraform_apply_prod
          stage: prod
          requires: [approval_deploy]
          filters:
            branches:
              only: main
