version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  node:
    docker:
      - image: node:12.19.0
  terraform:
    docker:
      - image: hashicorp/terraform:0.13.5

commands:
  terraform:
    parameters:
      command:
        type: string
    steps:
      - run:
          name: terraform << parameters.command >>
          command: |
            cd ~/project/terraform/
            terraform << parameters.command >>

  yarn_install:
    steps:
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --check-files
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  setup_aws_config:
    steps:
      - run:
          name: create aws/credentials aws/config
          command: |
            mkdir -p ~/.aws
            echo '[default]'                                       > ~/.aws/credentials
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}"         >> ~/.aws/credentials
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            echo '[default]'                                       > ~/.aws/config
            echo "region = us-east-1"                             >> ~/.aws/config

jobs:
  test:
    executor: node
    steps:
      - checkout
      - yarn_install
      - run: yarn run lint
      - run: yarn run build
      - slack/status

  terraform_plan:
    executor: terraform
    steps:
      - checkout
      - run: apk --update add curl bash
      - setup_aws_config
      - terraform:
          command: init
      - terraform:
          command: plan
      - slack/status

  terraform_apply:
    executor: terraform
    steps:
      - checkout
      - run: apk --update add curl bash
      - setup_aws_config
      - terraform:
          command: init
      - terraform:
          command: apply -auto-approve
      - slack/status

workflows:
  build:
    jobs:
      - test
      - terraform_plan
      - terraform_apply:
          requires: [terraform_plan]
          filters:
            branches:
              only: main
